#!/bin/bash
set -e # Exit immediately if a command exits with a non-zero status

# --- Configuration ---
REPO_PATH="."  # Current directory is the root of the cloned repo
BRANCH_NAME="bugfix-$(date +%s)"
COMMIT_MESSAGE="feat(cline): autonomous fix for lint issues"

echo "Starting autonomous bug fixer on branch: $BRANCH_NAME"
echo "--------------------------------------------------------"

# 1. Setup Git
git config user.email "bughunter-bot@github.com"
git config user.name "BugHunter Bot"

# 2. Create and switch to a new branch
git checkout -b "$BRANCH_NAME"

# 3. Install dependencies
echo "Installing dependencies..."
npm install

# 4. Run ESLint and capture output
echo "Running ESLint..."
LINT_FILE="lint.json"
npx eslint . --format json --output-file "$LINT_FILE" || true 

echo "--- DEBUG: LINT.JSON CONTENT ---"
# 🛑 ADDED: Print the content of lint.json to verify ESLint found errors.
cat "$LINT_FILE" 

# 5. Run Cline to generate the patch
echo "Running Cline to generate patch..."
PATCH_FILE="patch.diff"
SUMMARY_FILE="cline_summary.txt"

# 🛑 MODIFIED: Redirect STDOUT/STDERR of cline run to the terminal for debugging
cline run \
  --prompt-file="./prompts/fix-dry-run.md" \
  --input "$LINT_FILE" \
  --repo="." \
  --output "$PATCH_FILE" \
  > "$SUMMARY_FILE" 2>&1 || true

echo "--- DEBUG: CLINE SUMMARY (STDOUT/STDERR) ---"
# 🛑 ADDED: Print the Cline summary to see if it reports a connection error or a reason for skipping.
cat "$SUMMARY_FILE"

# 6. Apply patch and commit
if [ -s "$PATCH_FILE" ]; then
    echo "Patch generated. Applying fix..."
    git apply "$PATCH_FILE"
    git add .
    git commit -m "$COMMIT_MESSAGE" -m "$(cat $SUMMARY_FILE)"
    
    # 7. Push to GitHub
    echo "Pushing changes to branch $BRANCH_NAME..."
    # IMPORTANT: We use the GITHUB_TOKEN provided by GitHub Actions
    git push origin "$BRANCH_NAME"
    
    # 8. Create Pull Request
    echo "Creating Pull Request..."
    PR_TITLE="BugHunter: Autonomous Fix by Cline ($BRANCH_NAME)"
    PR_BODY_CONTENT=$(cat $SUMMARY_FILE)

    # Use GitHub CLI (gh) to create the PR, which is available in GitHub Actions runners
    gh pr create --title "$PR_TITLE" --body "$PR_BODY_CONTENT" --base main --head "$BRANCH_NAME"
    
else
    echo "No patch generated by Cline. Exiting successfully."
fi

echo "--------------------------------------------------------"
echo "Pipeline finished."