#!/bin/bash
set -e

# --- Configuration ---

# 🛑 Get arguments: $1=RepoURL, $2=API_KEY, $3=MODEL_ID
REPO_URL="$1" 
MY_AI_API_KEY="$2"
MODEL_ID="$3"

if [ -z "$REPO_URL" ] || [ -z "$MY_AI_API_KEY" ] || [ -z "$MODEL_ID" ]; then
    echo "Error: Required arguments are missing."
    exit 1
fi

TARGET_DIR="target_repo"
BRANCH_NAME="bugfix-$(date +%s)"
COMMIT_MESSAGE="feat(cline): autonomous fix for lint issues"

echo "Starting autonomous bug fixer on branch: $BRANCH_NAME"
echo "--------------------------------------------------------"

# 1. Setup Git
git config user.email "bughunter-bot@github.com"
git config user.name "BugHunter Bot"

# 2. Clone the TARGET repository
echo "Cloning target repo: $REPO_URL into $TARGET_DIR"
git clone "$REPO_URL" "$TARGET_DIR"

# 3. Enter the target repository
cd "$TARGET_DIR"

# 4. Create and switch to a new branch
git checkout -b "$BRANCH_NAME"

# 5. Install dependencies
echo "Installing dependencies..."
npm install

# 6. AUTHENTICATE CLINE (The FIX for the TTY error)
echo "Authenticating Cline CLI..."
# We use the explicit auth command from your example
cline auth --provider openai-native --apikey "$MY_AI_API_KEY" --modelid "$MODEL_ID"

# 7. Run ESLint and capture output
echo "Running ESLint..."
LINT_FILE="lint.json"
npx eslint . --format json --output-file "$LINT_FILE" || true 

echo "--- DEBUG: LINT.JSON CONTENT ---"
cat "$LINT_FILE" 

# 8. Run Cline to generate the patch
echo "Running Cline to generate patch..."
PATCH_FILE="patch.diff"
SUMMARY_FILE="cline_summary.txt"

# 🛑 We use the confirmed working syntax: prompt + non-interactive flags
cline "Review the attached lint.json file and generate a git patch to fix all issues." \
  -y \
  -o \
  -f "$LINT_FILE" \
  --no-interactive \
  > "$SUMMARY_FILE" 2>&1 || true

echo "--- DEBUG: CLINE SUMMARY (STDOUT/STDERR) ---"
cat "$SUMMARY_FILE"

# 9. Apply patch and commit (Remainder of logic remains the same)
if [ -s "$PATCH_FILE" ]; then
    echo "Patch generated. Applying fix..."
    git apply "$PATCH_FILE"
    git add .
    
    # ... (rest of commit and push logic) ...
else
    echo "No patch generated by Cline. Exiting successfully."
fi

# ... (rest of the file)